/**
 * Document Processing Log Types
 *
 * Defines the structure for tracking document processing through the extraction pipeline.
 */

/**
 * Processing stage names that map to the pipeline steps
 */
export type ProcessingStage =
  | 'upload' // File received in browser
  | 'pdf_extraction' // Text extraction via pdf.js
  | 'ocr_decision' // OCR Decision Engine analysis (language, policy type, quality)
  | 'ocr_check' // Legacy: Density check to determine if OCR needed
  | 'ocr_processing' // OCR via Document AI/Vision/Tesseract
  | 'gemini_ocr' // Gemini multimodal OCR fallback (when Document AI + pdf.js both fail)
  | 'text_preprocessing' // Text normalization, OCR cleanup
  | 'ai_extraction' // GPT-4o/Claude structured extraction
  | 'form_field_enhancement' // Document AI form fields applied
  | 'table_parsing' // Coverage table parsing
  | 'validation' // Data validation (Zod, business rules)
  | 'duplicate_check' // Duplicate/amendment detection
  | 'conflict_resolution' // User resolved duplicate conflict
  | 'database_save' // Save to Supabase
  | 'actuarial_evaluation' // Post-extraction actuarial engine evaluation

/**
 * Status of a processing stage
 */
export type ProcessingStageStatus =
  | 'pending' // Not started
  | 'running' // In progress
  | 'completed' // Finished successfully
  | 'failed' // Failed with error
  | 'skipped' // Skipped (e.g., OCR not needed)
  | 'partial' // Completed with warnings

/**
 * Overall document processing status
 */
export type ProcessingStatus =
  | 'pending' // Queued but not started
  | 'processing' // Currently being processed
  | 'completed' // All stages finished successfully
  | 'failed' // Processing failed
  | 'partial' // Some stages failed but document was saved

/**
 * Decision context for skipped stages - explains WHY a stage was skipped
 */
export interface StageDecisionContext {
  assessment_performed: string // What was checked (e.g., "Text density analysis")
  threshold?: {
    name: string // e.g., "chars_per_page"
    value: number // The threshold value (e.g., 200)
    unit?: string // e.g., "characters per page"
    comparison: 'less_than' | 'greater_than' | 'equals' | 'not_equals'
  }
  actual_values: Record<string, number | string | boolean> // Actual measured values
  decision_logic: string // How the decision was made
  alternatives?: string[] // What would have triggered the stage
  documentation_url?: string // Link to relevant docs
}

/**
 * A single processing stage record
 */
export interface ProcessingStageRecord {
  stage: ProcessingStage
  status: ProcessingStageStatus
  started_at: string // ISO timestamp
  completed_at?: string // ISO timestamp
  duration_ms?: number
  input?: Record<string, unknown>
  output?: Record<string, unknown>
  metadata?: Record<string, unknown>
  error?: string

  // Full text content for admin debugging
  // These are stored separately to allow UI to show previews first
  full_input_text?: string // Full input text before this stage
  full_output_text?: string // Full output text after this stage
  full_extracted_json?: string // Full extracted JSON (for ai_extraction stage)
  diff_summary?: {
    // Text difference summary for preprocessing stages
    characters_added: number
    characters_removed: number
    lines_changed: number
    major_changes: string[] // List of significant changes made
  }

  // Decision context for skipped stages - explains WHY it was skipped
  decision_context?: StageDecisionContext
}

/**
 * Summary of extracted policy data (for display before full policy exists)
 */
export interface ExtractedSummary {
  policy_number?: string
  provider?: string
  type?: string
  type_tr?: string
  insured_person?: string
  premium?: number
  coverage?: number
  start_date?: string
  expiry_date?: string
}

/**
 * Complete document processing log record
 */
export interface DocumentProcessingLog {
  id?: string // Auto-generated by database, optional when creating
  document_id: string
  policy_id?: string
  user_id?: string

  // File metadata
  filename: string
  file_size?: number
  mime_type?: string
  page_count?: number

  // Processing data
  stages: ProcessingStageRecord[]
  status: ProcessingStatus

  // Timing
  started_at: string
  completed_at?: string
  total_duration_ms?: number

  // Error tracking - enhanced for admin visibility
  error_message?: string
  error_stage?: string
  error_details?: Record<string, unknown>
  // Detailed error information for debugging
  error_stack?: string
  error_type?: string
  error_code?: string
  error_context?: {
    extraction_provider?: string
    document_length?: number
    ocr_used?: boolean
    error_code?: string
    last_successful_stage?: string
    data_at_failure?: Record<string, unknown>
    browser_info?: string
    timestamp?: string
  }

  // Request correlation
  request_id?: string // Links frontend extraction to server-side logs

  // Summary flags for filtering
  ocr_used: boolean
  ocr_engine?: string
  ai_provider?: string
  extraction_confidence?: number

  // Route and fallback tracking
  extraction_route?: string // Server endpoint used (e.g., '/api/ai/extract', '/api/ai/extract/openai')
  extraction_mode?: 'proxy' | 'direct' | 'consensus' // How extraction was invoked
  fallback_used?: boolean // True if primary provider failed and fallback was used
  fallback_chain?: Array<{
    // Full provider attempt chain
    provider: string // e.g., 'anthropic', 'openai'
    success: boolean
    duration_ms?: number
    error?: string // Error message if failed
    error_code?: string // Structured error code (e.g., 'ANTHROPIC_BILLING_ERROR')
  }>

  // Extracted summary
  extracted_summary?: ExtractedSummary

  created_at: string
  updated_at: string
}

/**
 * Stage configuration for UI display
 */
export interface StageConfig {
  name: ProcessingStage
  label: string
  labelTr: string
  description: string
  descriptionTr: string
  icon: string // Lucide icon name
  color: string // Tailwind color class
}

/**
 * Stage configurations for the pipeline visualization
 */
export const STAGE_CONFIGS: Record<ProcessingStage, StageConfig> = {
  upload: {
    name: 'upload',
    label: 'Upload',
    labelTr: 'Yükleme',
    description: 'File received and validated',
    descriptionTr: 'Dosya alındı ve doğrulandı',
    icon: 'Upload',
    color: 'blue',
  },
  pdf_extraction: {
    name: 'pdf_extraction',
    label: 'PDF Extraction',
    labelTr: 'PDF Metin Çıkarma',
    description: 'Text extracted from PDF using pdf.js',
    descriptionTr: "pdf.js ile PDF'den metin çıkarıldı",
    icon: 'FileText',
    color: 'indigo',
  },
  ocr_decision: {
    name: 'ocr_decision',
    label: 'OCR Decision',
    labelTr: 'OCR Karar Motoru',
    description: 'Analyzing document quality to determine OCR requirements',
    descriptionTr: 'OCR gereksinimini belirlemek için belge kalitesi analiz ediliyor',
    icon: 'BrainCircuit',
    color: 'purple',
  },
  ocr_check: {
    name: 'ocr_check',
    label: 'OCR Check',
    labelTr: 'OCR Kontrolü',
    description: 'Checking if OCR is needed based on text density',
    descriptionTr: 'Metin yoğunluğuna göre OCR gereksinimi kontrol edildi',
    icon: 'Search',
    color: 'purple',
  },
  ocr_processing: {
    name: 'ocr_processing',
    label: 'OCR Processing',
    labelTr: 'OCR İşleme',
    description: 'Optical Character Recognition for scanned documents',
    descriptionTr: 'Taranan belgeler için optik karakter tanıma',
    icon: 'ScanLine',
    color: 'violet',
  },
  gemini_ocr: {
    name: 'gemini_ocr',
    label: 'Gemini OCR',
    labelTr: 'Gemini OCR',
    description: 'Multimodal OCR fallback using Gemini 2.5 Flash',
    descriptionTr: 'Gemini 2.5 Flash ile çoklu ortam OCR yedek işlemi',
    icon: 'Sparkles',
    color: 'cyan',
  },
  text_preprocessing: {
    name: 'text_preprocessing',
    label: 'Text Preprocessing',
    labelTr: 'Metin Ön İşleme',
    description: 'Text normalization and OCR cleanup',
    descriptionTr: 'Metin normalizasyonu ve OCR temizliği',
    icon: 'Wand2',
    color: 'fuchsia',
  },
  ai_extraction: {
    name: 'ai_extraction',
    label: 'AI Extraction',
    labelTr: 'AI Çıkarma',
    description: 'Structured data extraction using AI (GPT-4o/Claude)',
    descriptionTr: 'AI ile yapılandırılmış veri çıkarma (GPT-4o/Claude)',
    icon: 'Brain',
    color: 'pink',
  },
  form_field_enhancement: {
    name: 'form_field_enhancement',
    label: 'Form Fields',
    labelTr: 'Form Alanları',
    description: 'Enhancement using Document AI form field detection',
    descriptionTr: 'Document AI form alanı tespiti ile zenginleştirme',
    icon: 'FormInput',
    color: 'rose',
  },
  table_parsing: {
    name: 'table_parsing',
    label: 'Table Parsing',
    labelTr: 'Tablo Ayrıştırma',
    description: 'Coverage table extraction and parsing',
    descriptionTr: 'Teminat tablosu çıkarma ve ayrıştırma',
    icon: 'Table',
    color: 'orange',
  },
  validation: {
    name: 'validation',
    label: 'Validation',
    labelTr: 'Doğrulama',
    description: 'Data validation and business rules check',
    descriptionTr: 'Veri doğrulama ve iş kuralları kontrolü',
    icon: 'CheckCircle',
    color: 'amber',
  },
  duplicate_check: {
    name: 'duplicate_check',
    label: 'Duplicate Check',
    labelTr: 'Mükerrer Kontrol',
    description: 'Checking for existing similar policies',
    descriptionTr: 'Mevcut benzer poliçeler kontrol edildi',
    icon: 'Copy',
    color: 'yellow',
  },
  conflict_resolution: {
    name: 'conflict_resolution',
    label: 'Conflict Resolution',
    labelTr: 'Çakışma Çözümü',
    description: 'User resolved duplicate/amendment conflict',
    descriptionTr: 'Kullanıcı mükerrer/değişiklik çakışmasını çözdü',
    icon: 'GitMerge',
    color: 'lime',
  },
  database_save: {
    name: 'database_save',
    label: 'Save',
    labelTr: 'Kayıt',
    description: 'Policy saved to database',
    descriptionTr: 'Poliçe veritabanına kaydedildi',
    icon: 'Database',
    color: 'green',
  },
  actuarial_evaluation: {
    name: 'actuarial_evaluation',
    label: 'Actuarial Evaluation',
    labelTr: 'Aktüeryal Değerlendirme',
    description: 'Actuarial scoring (Monte Carlo & TOPSIS)',
    descriptionTr: 'Aktüeryal skorlama (Monte Carlo ve TOPSIS)',
    icon: 'Calculator',
    color: 'teal',
  },
}

/**
 * Get ordered list of stages for pipeline display
 */
export const PIPELINE_STAGES: ProcessingStage[] = [
  'upload',
  'pdf_extraction',
  'ocr_decision',
  'ocr_check', // Legacy - kept for backwards compatibility
  'ocr_processing',
  'gemini_ocr',
  'text_preprocessing',
  'ai_extraction',
  'form_field_enhancement',
  'table_parsing',
  'validation',
  'duplicate_check',
  'conflict_resolution',
  'database_save',
  'actuarial_evaluation',
]
