/**
 * Policy Template Library Data
 * Best practice templates for Turkish insurance market
 */

import type { PolicyType } from '@/types/policy'
import type {
  PolicyTemplate,
  TemplateCoverage,
  BestPractice,
  CoverageTier,
} from '@/types/policy-template'

// =============================================================================
// Home Insurance Templates
// =============================================================================

const HOME_COVERAGES_BASIC: TemplateCoverage[] = [
  {
    name: 'Fire',
    nameTr: 'Yangın',
    category: 'core',
    description: 'Protection against fire damage',
    descriptionTr: 'Yangın hasarlarına karşı koruma',
    minLimit: 300000,
    recommendedLimit: 500000,
    maxLimit: 2000000,
    typicalDeductible: 1000,
    importance: 'critical',
    rationale: 'Essential protection for property value',
    rationaleTr: 'Mülk değeri için temel koruma',
    watchExclusions: ['intentional fire', 'unoccupied property over 30 days'],
    watchExclusionsTr: ['kasıtlı yangın', '30 günden fazla boş mülk'],
  },
  {
    name: 'Natural Disasters',
    nameTr: 'Doğal Afetler',
    category: 'core',
    description: 'Storm, flood, and natural disaster coverage',
    descriptionTr: 'Fırtına, sel ve doğal afet teminatı',
    minLimit: 200000,
    recommendedLimit: 400000,
    maxLimit: 1500000,
    typicalDeductible: 2000,
    importance: 'critical',
    rationale: 'Climate-related risks are increasing',
    rationaleTr: 'İklimle ilgili riskler artıyor',
    watchExclusions: ['earthquake (separate DASK)', 'landslide in high-risk zones'],
    watchExclusionsTr: ['deprem (ayrı DASK)', 'yüksek riskli bölgelerde heyelan'],
  },
  {
    name: 'Theft',
    nameTr: 'Hırsızlık',
    category: 'core',
    description: 'Burglary and theft protection',
    descriptionTr: 'Hırsızlık ve soygun koruması',
    minLimit: 30000,
    recommendedLimit: 75000,
    maxLimit: 300000,
    typicalDeductible: 500,
    importance: 'high',
    rationale: 'Common risk in urban areas',
    rationaleTr: 'Kentsel alanlarda yaygın risk',
    watchExclusions: ['unlocked doors/windows', 'jewelry over limit'],
    watchExclusionsTr: ['kilitlenmemiş kapı/pencere', 'limit üstü mücevher'],
  },
]

const HOME_COVERAGES_STANDARD: TemplateCoverage[] = [
  ...HOME_COVERAGES_BASIC.map((c) => ({
    ...c,
    minLimit: c.minLimit * 1.3,
    recommendedLimit: c.recommendedLimit * 1.3,
  })),
  {
    name: 'Water Damage',
    nameTr: 'Su Hasarı',
    category: 'recommended',
    description: 'Plumbing and water damage coverage',
    descriptionTr: 'Tesisat ve su hasarı teminatı',
    minLimit: 20000,
    recommendedLimit: 50000,
    maxLimit: 150000,
    typicalDeductible: 500,
    importance: 'high',
    rationale: 'Most common home insurance claim',
    rationaleTr: 'En yaygın konut sigortası talebi',
    watchExclusions: ['gradual leaks', 'poor maintenance'],
    watchExclusionsTr: ['yavaş sızıntılar', 'bakım eksikliği'],
  },
  {
    name: 'Glass Breakage',
    nameTr: 'Cam Kırılması',
    category: 'recommended',
    description: 'Window and glass coverage',
    descriptionTr: 'Pencere ve cam teminatı',
    minLimit: 10000,
    recommendedLimit: 25000,
    maxLimit: 75000,
    typicalDeductible: 250,
    importance: 'medium',
    rationale: 'Common issue, especially in apartments',
    rationaleTr: 'Özellikle apartmanlarda yaygın sorun',
    watchExclusions: ['cosmetic damage', 'existing cracks'],
    watchExclusionsTr: ['kozmetik hasar', 'mevcut çatlaklar'],
  },
  {
    name: 'Liability',
    nameTr: 'Sorumluluk',
    category: 'recommended',
    description: 'Third-party liability coverage',
    descriptionTr: 'Üçüncü şahıs sorumluluk teminatı',
    minLimit: 50000,
    recommendedLimit: 100000,
    maxLimit: 500000,
    typicalDeductible: 1000,
    importance: 'high',
    rationale: 'Protects against lawsuits from guests',
    rationaleTr: 'Misafirlerden gelen davalara karşı korur',
    watchExclusions: ['intentional acts', 'business activities'],
    watchExclusionsTr: ['kasıtlı eylemler', 'ticari faaliyetler'],
  },
]

const HOME_COVERAGES_COMPREHENSIVE: TemplateCoverage[] = [
  ...HOME_COVERAGES_STANDARD.map((c) => ({
    ...c,
    minLimit: c.minLimit * 1.5,
    recommendedLimit: c.recommendedLimit * 1.5,
  })),
  {
    name: 'Electrical Damage',
    nameTr: 'Elektrik Hasarı',
    category: 'recommended',
    description: 'Electronic and electrical equipment coverage',
    descriptionTr: 'Elektronik ve elektrikli cihaz teminatı',
    minLimit: 15000,
    recommendedLimit: 40000,
    maxLimit: 100000,
    typicalDeductible: 500,
    importance: 'medium',
    rationale: 'Power surges and outages are common',
    rationaleTr: 'Elektrik dalgalanmaları ve kesintiler yaygın',
    watchExclusions: ['devices over 5 years old', 'commercial equipment'],
    watchExclusionsTr: ['5 yıldan eski cihazlar', 'ticari ekipmanlar'],
  },
  {
    name: 'Alternative Living Expenses',
    nameTr: 'Alternatif Konaklama Giderleri',
    category: 'recommended',
    description: 'Temporary housing if home is uninhabitable',
    descriptionTr: 'Ev yaşanmaz hale gelirse geçici konaklama',
    minLimit: 20000,
    recommendedLimit: 50000,
    maxLimit: 150000,
    typicalDeductible: 0,
    importance: 'high',
    rationale: 'Crucial if major damage occurs',
    rationaleTr: 'Büyük hasar durumunda kritik',
    watchExclusions: ['evacuation by choice', 'non-covered damage'],
    watchExclusionsTr: ['kendi isteğiyle tahliye', 'teminat dışı hasar'],
  },
  {
    name: 'Valuable Items',
    nameTr: 'Değerli Eşyalar',
    category: 'optional',
    description: 'Jewelry, art, and collectibles',
    descriptionTr: 'Mücevher, sanat eseri ve koleksiyonlar',
    minLimit: 20000,
    recommendedLimit: 75000,
    maxLimit: 500000,
    typicalDeductible: 1000,
    importance: 'medium',
    rationale: 'Standard policies have low sub-limits',
    rationaleTr: 'Standart poliçelerde düşük alt limitler var',
    watchExclusions: ['items not appraised', 'mysterious disappearance'],
    watchExclusionsTr: ['değerleme yapılmamış eşyalar', 'esrarengiz kaybolma'],
  },
]

const HOME_BEST_PRACTICES: BestPractice[] = [
  {
    id: 'home-bp-1',
    title: 'Annual Coverage Review',
    titleTr: 'Yıllık Teminat Değerlendirmesi',
    description: 'Review and update coverage amounts annually',
    descriptionTr: 'Teminat tutarlarını yıllık olarak gözden geçirin ve güncelleyin',
    category: 'coverage',
    priority: 'essential',
    guidance: [
      'Reassess home value with inflation',
      'Update contents inventory',
      'Review any home improvements',
      'Check if coverage meets mortgage requirements',
    ],
    guidanceTr: [
      'Enflasyonla ev değerini yeniden değerlendirin',
      'Eşya envanterini güncelleyin',
      'Ev tadilatlarını gözden geçirin',
      'Teminatın ipotek gereksinimlerini karşılayıp karşılamadığını kontrol edin',
    ],
    pitfalls: [
      'Underinsurance due to property appreciation',
      'Forgetting to add new valuables',
      'Missing required renovations coverage',
    ],
    pitfallsTr: [
      'Mülk değer artışı nedeniyle eksik sigortalama',
      'Yeni değerli eşyaları eklemeyi unutmak',
      'Gerekli tadilat teminatını kaçırmak',
    ],
  },
  {
    id: 'home-bp-2',
    title: 'DASK Integration',
    titleTr: 'DASK Entegrasyonu',
    description: 'Ensure earthquake coverage is properly coordinated',
    descriptionTr: 'Deprem teminatının düzgün şekilde koordine edildiğinden emin olun',
    category: 'coverage',
    priority: 'essential',
    guidance: [
      'Verify DASK policy is active',
      'Understand the gap between DASK and home policy',
      'Consider supplemental earthquake coverage',
      'Check building structural class',
    ],
    guidanceTr: [
      'DASK poliçesinin aktif olduğunu doğrulayın',
      'DASK ile konut poliçesi arasındaki boşluğu anlayın',
      'Ek deprem teminatı düşünün',
      'Bina yapısal sınıfını kontrol edin',
    ],
    pitfalls: [
      'Assuming home policy covers earthquake',
      'DASK coverage gaps for valuable homes',
      'Expired DASK without notification',
    ],
    pitfallsTr: [
      'Konut poliçesinin depremi kapsadığını varsaymak',
      'Değerli evler için DASK teminat boşlukları',
      'Bildirimsiz süresi dolmuş DASK',
    ],
  },
  {
    id: 'home-bp-3',
    title: 'Document Your Belongings',
    titleTr: 'Eşyalarınızı Belgeleyin',
    description: 'Maintain an inventory with photos and receipts',
    descriptionTr: 'Fotoğraf ve faturalarla envanter tutun',
    category: 'claims',
    priority: 'recommended',
    guidance: [
      'Take photos or videos of all rooms',
      'Keep receipts for major purchases',
      'Store inventory in cloud or safe deposit box',
      'Update inventory after major purchases',
    ],
    guidanceTr: [
      'Tüm odaların fotoğrafını veya videosunu çekin',
      'Büyük alımların faturalarını saklayın',
      'Envanteri bulutta veya kasada saklayın',
      'Büyük alımlardan sonra envanteri güncelleyin',
    ],
    pitfalls: [
      'Claiming without proof reduces payouts',
      'Outdated inventory misses new items',
      'Local storage destroyed with home',
    ],
    pitfallsTr: [
      'Kanıtsız talep ödemeleri azaltır',
      'Güncel olmayan envanter yeni eşyaları kaçırır',
      'Yerel depolama evle birlikte yok olur',
    ],
  },
]

export const HOME_TEMPLATES: PolicyTemplate[] = [
  {
    id: 'home-basic',
    name: 'Basic Home Protection',
    nameTr: 'Temel Konut Koruması',
    description: 'Essential coverage meeting minimum requirements',
    descriptionTr: 'Minimum gereksinimleri karşılayan temel teminat',
    policyType: 'home',
    tier: 'basic',
    audience: 'individual',
    useCases: ['first_time_buyer', 'cost_optimization'],
    coverages: HOME_COVERAGES_BASIC,
    estimatedPremiumRange: { min: 1500, max: 3000, typical: 2000 },
    bestPractices: HOME_BEST_PRACTICES.filter((bp) => bp.priority === 'essential'),
    highlights: [
      'Core fire and theft protection',
      'Natural disaster coverage',
      'Affordable premium',
    ],
    highlightsTr: [
      'Temel yangın ve hırsızlık koruması',
      'Doğal afet teminatı',
      'Uygun prim',
    ],
    suitableFor: ['Renters with minimal belongings', 'Budget-conscious homeowners', 'Low-risk areas'],
    suitableForTr: ['Minimal eşyası olan kiracılar', 'Bütçe bilincinde ev sahipleri', 'Düşük riskli bölgeler'],
    notSuitableFor: ['Valuable home contents', 'High-risk areas', 'Families with dependents'],
    notSuitableForTr: ['Değerli ev eşyaları', 'Yüksek riskli bölgeler', 'Bağımlıları olan aileler'],
    version: '1.0',
    lastUpdated: '2024-12-01',
    source: 'market_analysis',
    tags: ['basic', 'budget', 'essential', 'starter'],
    tagsTr: ['temel', 'bütçe', 'zorunlu', 'başlangıç'],
  },
  {
    id: 'home-standard',
    name: 'Standard Home Protection',
    nameTr: 'Standart Konut Koruması',
    description: 'Balanced coverage for typical homeowner needs',
    descriptionTr: 'Tipik ev sahibi ihtiyaçları için dengeli teminat',
    policyType: 'home',
    tier: 'standard',
    audience: 'family',
    useCases: ['renewal', 'upgrade'],
    coverages: HOME_COVERAGES_STANDARD,
    estimatedPremiumRange: { min: 3000, max: 6000, typical: 4000 },
    bestPractices: HOME_BEST_PRACTICES,
    highlights: [
      'Water damage protection',
      'Liability coverage included',
      'Glass breakage coverage',
      'Higher limits across all categories',
    ],
    highlightsTr: [
      'Su hasarı koruması',
      'Sorumluluk teminatı dahil',
      'Cam kırılması teminatı',
      'Tüm kategorilerde daha yüksek limitler',
    ],
    suitableFor: ['Average homeowners', 'Families', 'Apartment owners'],
    suitableForTr: ['Ortalama ev sahipleri', 'Aileler', 'Daire sahipleri'],
    notSuitableFor: ['Luxury homes', 'High-value art collections', 'Commercial properties'],
    notSuitableForTr: ['Lüks evler', 'Yüksek değerli sanat koleksiyonları', 'Ticari mülkler'],
    comparedToBasic: [
      'Water damage coverage added',
      'Liability protection included',
      '30% higher limits on core coverages',
    ],
    comparedToBasicTr: [
      'Su hasarı teminatı eklendi',
      'Sorumluluk koruması dahil',
      'Temel teminatlarda %30 daha yüksek limitler',
    ],
    version: '1.0',
    lastUpdated: '2024-12-01',
    source: 'market_analysis',
    tags: ['standard', 'family', 'balanced', 'recommended'],
    tagsTr: ['standart', 'aile', 'dengeli', 'önerilen'],
  },
  {
    id: 'home-comprehensive',
    name: 'Comprehensive Home Protection',
    nameTr: 'Kapsamlı Konut Koruması',
    description: 'Extensive coverage with additional protections',
    descriptionTr: 'Ek korumalarla geniş kapsamlı teminat',
    policyType: 'home',
    tier: 'comprehensive',
    audience: 'family',
    useCases: ['comprehensive_review', 'risk_mitigation'],
    coverages: HOME_COVERAGES_COMPREHENSIVE,
    estimatedPremiumRange: { min: 6000, max: 12000, typical: 8000 },
    bestPractices: HOME_BEST_PRACTICES,
    highlights: [
      'Alternative living expenses covered',
      'Valuable items protection',
      'Electrical damage coverage',
      'Higher deductibles for cost savings',
      'Premium limits on all coverages',
    ],
    highlightsTr: [
      'Alternatif konaklama giderleri kapsam dahilinde',
      'Değerli eşya koruması',
      'Elektrik hasarı teminatı',
      'Maliyet tasarrufu için daha yüksek muafiyetler',
      'Tüm teminatlarda premium limitler',
    ],
    suitableFor: ['Affluent homeowners', 'Valuable home contents', 'Risk-averse families'],
    suitableForTr: ['Varlıklı ev sahipleri', 'Değerli ev eşyaları', 'Riskten kaçınan aileler'],
    notSuitableFor: ['Budget constraints', 'Minimal belongings', 'Short-term rentals'],
    notSuitableForTr: ['Bütçe kısıtlamaları', 'Minimal eşya', 'Kısa süreli kiralamalar'],
    comparedToBasic: [
      '50% higher limits',
      'Alternative living expenses included',
      'Valuable items coverage',
      'Electrical damage protection',
    ],
    comparedToBasicTr: [
      '%50 daha yüksek limitler',
      'Alternatif konaklama giderleri dahil',
      'Değerli eşya teminatı',
      'Elektrik hasarı koruması',
    ],
    version: '1.0',
    lastUpdated: '2024-12-01',
    source: 'market_analysis',
    tags: ['comprehensive', 'premium', 'full-coverage', 'valuable'],
    tagsTr: ['kapsamlı', 'premium', 'tam-teminat', 'değerli'],
  },
]

// =============================================================================
// Auto Insurance Templates (Kasko)
// =============================================================================

const KASKO_COVERAGES_BASIC: TemplateCoverage[] = [
  {
    name: 'Collision',
    nameTr: 'Çarpışma',
    category: 'core',
    description: 'Collision damage to your vehicle',
    descriptionTr: 'Aracınızın çarpışma hasarı',
    minLimit: 100000,
    recommendedLimit: 200000,
    maxLimit: 1000000,
    typicalDeductible: 2000,
    importance: 'critical',
    rationale: 'Core protection for vehicle investment',
    rationaleTr: 'Araç yatırımı için temel koruma',
    watchExclusions: ['racing', 'unlicensed drivers'],
    watchExclusionsTr: ['yarış', 'ehliyetsiz sürücüler'],
  },
  {
    name: 'Theft',
    nameTr: 'Hırsızlık',
    category: 'core',
    description: 'Total or partial vehicle theft',
    descriptionTr: 'Tam veya kısmi araç hırsızlığı',
    minLimit: 100000,
    recommendedLimit: 200000,
    maxLimit: 1000000,
    typicalDeductible: 1000,
    importance: 'critical',
    rationale: 'High theft rates in urban areas',
    rationaleTr: 'Kentsel alanlarda yüksek hırsızlık oranları',
    watchExclusions: ['keys left in vehicle', 'unlocked vehicle'],
    watchExclusionsTr: ['araçta bırakılan anahtarlar', 'kilitlenmemiş araç'],
  },
  {
    name: 'Fire',
    nameTr: 'Yangın',
    category: 'core',
    description: 'Fire and explosion damage',
    descriptionTr: 'Yangın ve patlama hasarı',
    minLimit: 100000,
    recommendedLimit: 200000,
    maxLimit: 1000000,
    typicalDeductible: 1500,
    importance: 'high',
    rationale: 'Protects against total loss from fire',
    rationaleTr: 'Yangından kaynaklanan tam kayba karşı korur',
    watchExclusions: ['arson by policyholder', 'mechanical fire'],
    watchExclusionsTr: ['poliçe sahibi tarafından kundaklama', 'mekanik yangın'],
  },
]

const KASKO_COVERAGES_STANDARD: TemplateCoverage[] = [
  ...KASKO_COVERAGES_BASIC.map((c) => ({
    ...c,
    recommendedLimit: c.recommendedLimit * 1.5,
    typicalDeductible: c.typicalDeductible * 0.8,
  })),
  {
    name: 'Glass',
    nameTr: 'Cam',
    category: 'recommended',
    description: 'Windshield and window coverage',
    descriptionTr: 'Ön cam ve pencere teminatı',
    minLimit: 5000,
    recommendedLimit: 15000,
    maxLimit: 50000,
    typicalDeductible: 0,
    importance: 'high',
    rationale: 'Common claim, zero deductible is standard',
    rationaleTr: 'Yaygın talep, sıfır muafiyet standart',
    watchExclusions: ['cosmetic scratches', 'tinting damage'],
    watchExclusionsTr: ['kozmetik çizikler', 'renklendirme hasarı'],
  },
  {
    name: 'Natural Disasters',
    nameTr: 'Doğal Afetler',
    category: 'recommended',
    description: 'Flood, hail, and storm damage',
    descriptionTr: 'Sel, dolu ve fırtına hasarı',
    minLimit: 50000,
    recommendedLimit: 150000,
    maxLimit: 500000,
    typicalDeductible: 2000,
    importance: 'high',
    rationale: 'Climate events are increasing',
    rationaleTr: 'İklim olayları artıyor',
    watchExclusions: ['driving into flood', 'ignored warnings'],
    watchExclusionsTr: ['sele sürme', 'yok sayılan uyarılar'],
  },
  {
    name: 'Personal Effects',
    nameTr: 'Kişisel Eşyalar',
    category: 'optional',
    description: 'Personal belongings in vehicle',
    descriptionTr: 'Araçtaki kişisel eşyalar',
    minLimit: 2000,
    recommendedLimit: 5000,
    maxLimit: 25000,
    typicalDeductible: 500,
    importance: 'low',
    rationale: 'Covers items stolen from car',
    rationaleTr: 'Arabadan çalınan eşyaları kapsar',
    watchExclusions: ['visible items', 'electronics over limit'],
    watchExclusionsTr: ['görünür eşyalar', 'limit üstü elektronikler'],
  },
]

const KASKO_BEST_PRACTICES: BestPractice[] = [
  {
    id: 'kasko-bp-1',
    title: 'Maintain Original Value Coverage',
    titleTr: 'Orijinal Değer Teminatını Koruyun',
    description: 'Ensure coverage reflects current market value',
    descriptionTr: 'Teminatın güncel piyasa değerini yansıttığından emin olun',
    category: 'coverage',
    priority: 'essential',
    guidance: [
      'Update vehicle value annually',
      'Consider agreed value policies for classics',
      'Factor in modifications and upgrades',
      'Review depreciation schedule',
    ],
    guidanceTr: [
      'Araç değerini yıllık güncelleyin',
      'Klasikler için üzerinde anlaşılmış değer poliçeleri düşünün',
      'Modifikasyonları ve yükseltmeleri hesaba katın',
      'Amortisman takvimini gözden geçirin',
    ],
    pitfalls: [
      'Receiving less than replacement cost',
      'Not reporting modifications',
      'Outdated vehicle valuation',
    ],
    pitfallsTr: [
      'Yenileme maliyetinden az alma',
      'Modifikasyonları bildirmemek',
      'Güncel olmayan araç değerlemesi',
    ],
  },
  {
    id: 'kasko-bp-2',
    title: 'Zero Deductible for Glass',
    titleTr: 'Cam İçin Sıfır Muafiyet',
    description: 'Glass damage should have zero deductible',
    descriptionTr: 'Cam hasarının sıfır muafiyeti olmalı',
    category: 'deductibles',
    priority: 'recommended',
    guidance: [
      'Most policies offer zero glass deductible',
      'Windshield repairs prevent larger claims',
      'Compare glass coverage limits',
    ],
    guidanceTr: [
      'Çoğu poliçe sıfır cam muafiyeti sunar',
      'Ön cam onarımları daha büyük talepleri önler',
      'Cam teminat limitlerini karşılaştırın',
    ],
    pitfalls: [
      'Paying out of pocket for chips',
      'Small chips becoming cracks',
      'Choosing deductible to save premium',
    ],
    pitfallsTr: [
      'Küçük çatlaklar için cebinden ödemek',
      'Küçük çatlakların büyümesi',
      'Prim tasarrufu için muafiyet seçmek',
    ],
  },
]

export const KASKO_TEMPLATES: PolicyTemplate[] = [
  {
    id: 'kasko-basic',
    name: 'Basic Kasko',
    nameTr: 'Temel Kasko',
    description: 'Essential auto protection for standard vehicles',
    descriptionTr: 'Standart araçlar için temel oto koruması',
    policyType: 'kasko',
    tier: 'basic',
    audience: 'individual',
    useCases: ['first_time_buyer', 'cost_optimization'],
    coverages: KASKO_COVERAGES_BASIC,
    estimatedPremiumRange: { min: 5000, max: 15000, typical: 8000 },
    bestPractices: KASKO_BEST_PRACTICES.filter((bp) => bp.priority === 'essential'),
    highlights: ['Collision protection', 'Theft coverage', 'Fire and explosion'],
    highlightsTr: ['Çarpışma koruması', 'Hırsızlık teminatı', 'Yangın ve patlama'],
    suitableFor: ['Older vehicles', 'Low mileage drivers', 'Budget-conscious'],
    suitableForTr: ['Eski araçlar', 'Düşük kilometreli sürücüler', 'Bütçe bilincinde'],
    notSuitableFor: ['New vehicles', 'High-value cars', 'Frequent drivers'],
    notSuitableForTr: ['Yeni araçlar', 'Yüksek değerli arabalar', 'Sık sürücüler'],
    version: '1.0',
    lastUpdated: '2024-12-01',
    source: 'market_analysis',
    tags: ['basic', 'kasko', 'auto', 'budget'],
    tagsTr: ['temel', 'kasko', 'oto', 'bütçe'],
  },
  {
    id: 'kasko-standard',
    name: 'Standard Kasko',
    nameTr: 'Standart Kasko',
    description: 'Balanced auto protection with additional coverages',
    descriptionTr: 'Ek teminatlarla dengeli oto koruması',
    policyType: 'kasko',
    tier: 'standard',
    audience: 'individual',
    useCases: ['renewal', 'upgrade'],
    coverages: KASKO_COVERAGES_STANDARD,
    estimatedPremiumRange: { min: 10000, max: 25000, typical: 15000 },
    bestPractices: KASKO_BEST_PRACTICES,
    highlights: [
      'Zero deductible glass coverage',
      'Natural disaster protection',
      'Personal effects coverage',
      'Lower deductibles',
    ],
    highlightsTr: [
      'Sıfır muafiyetli cam teminatı',
      'Doğal afet koruması',
      'Kişisel eşya teminatı',
      'Daha düşük muafiyetler',
    ],
    suitableFor: ['Daily commuters', 'Average vehicles', 'Families'],
    suitableForTr: ['Günlük işe gidip gelenler', 'Ortalama araçlar', 'Aileler'],
    notSuitableFor: ['Classic cars', 'Luxury vehicles', 'Commercial use'],
    notSuitableForTr: ['Klasik arabalar', 'Lüks araçlar', 'Ticari kullanım'],
    comparedToBasic: [
      'Glass coverage added',
      'Natural disaster protection',
      '20% lower deductibles',
    ],
    comparedToBasicTr: [
      'Cam teminatı eklendi',
      'Doğal afet koruması',
      '%20 daha düşük muafiyetler',
    ],
    version: '1.0',
    lastUpdated: '2024-12-01',
    source: 'market_analysis',
    tags: ['standard', 'kasko', 'auto', 'recommended'],
    tagsTr: ['standart', 'kasko', 'oto', 'önerilen'],
  },
]

// =============================================================================
// Business Insurance Templates
// =============================================================================

const BUSINESS_COVERAGES_STANDARD: TemplateCoverage[] = [
  {
    name: 'Property',
    nameTr: 'Mülk',
    category: 'core',
    description: 'Building and contents coverage',
    descriptionTr: 'Bina ve içerik teminatı',
    minLimit: 500000,
    recommendedLimit: 1500000,
    maxLimit: 10000000,
    typicalDeductible: 5000,
    importance: 'critical',
    rationale: 'Protects business assets',
    rationaleTr: 'İşletme varlıklarını korur',
    watchExclusions: ['flood', 'earthquake', 'wear and tear'],
    watchExclusionsTr: ['sel', 'deprem', 'aşınma ve yıpranma'],
  },
  {
    name: 'Business Interruption',
    nameTr: 'İş Durması',
    category: 'core',
    description: 'Lost income during disruption',
    descriptionTr: 'Kesinti sırasında kayıp gelir',
    minLimit: 200000,
    recommendedLimit: 500000,
    maxLimit: 5000000,
    typicalDeductible: 0,
    importance: 'critical',
    rationale: 'Keeps business operational',
    rationaleTr: 'İşletmeyi çalışır durumda tutar',
    watchExclusions: ['pandemics', 'government orders'],
    watchExclusionsTr: ['pandemiler', 'devlet emirleri'],
  },
  {
    name: 'General Liability',
    nameTr: 'Genel Sorumluluk',
    category: 'core',
    description: 'Third-party injury and property damage',
    descriptionTr: 'Üçüncü şahıs yaralanması ve mülk hasarı',
    minLimit: 500000,
    recommendedLimit: 1000000,
    maxLimit: 5000000,
    typicalDeductible: 2500,
    importance: 'critical',
    rationale: 'Essential for any business with customers',
    rationaleTr: 'Müşterisi olan her işletme için gerekli',
    watchExclusions: ['intentional acts', 'contractual liability'],
    watchExclusionsTr: ['kasıtlı eylemler', 'sözleşmesel sorumluluk'],
  },
  {
    name: 'Employer Liability',
    nameTr: 'İşveren Sorumluluğu',
    category: 'core',
    description: 'Employee injury and illness claims',
    descriptionTr: 'Çalışan yaralanması ve hastalık talepleri',
    minLimit: 250000,
    recommendedLimit: 500000,
    maxLimit: 2000000,
    typicalDeductible: 0,
    importance: 'critical',
    rationale: 'Legal requirement for employers',
    rationaleTr: 'İşverenler için yasal gereklilik',
    watchExclusions: ['deliberate injury', 'unlicensed work'],
    watchExclusionsTr: ['kasıtlı yaralanma', 'lisanssız çalışma'],
  },
  {
    name: 'Cyber Liability',
    nameTr: 'Siber Sorumluluk',
    category: 'recommended',
    description: 'Data breach and cyber attack coverage',
    descriptionTr: 'Veri ihlali ve siber saldırı teminatı',
    minLimit: 100000,
    recommendedLimit: 500000,
    maxLimit: 5000000,
    typicalDeductible: 5000,
    importance: 'high',
    rationale: 'Critical for digital operations',
    rationaleTr: 'Dijital operasyonlar için kritik',
    watchExclusions: ['known vulnerabilities', 'outdated software'],
    watchExclusionsTr: ['bilinen güvenlik açıkları', 'güncel olmayan yazılım'],
  },
]

const BUSINESS_BEST_PRACTICES: BestPractice[] = [
  {
    id: 'business-bp-1',
    title: 'Business Continuity Planning',
    titleTr: 'İş Sürekliliği Planlaması',
    description: 'Align insurance with business continuity plan',
    descriptionTr: 'Sigortayı iş sürekliliği planıyla hizalayın',
    category: 'coverage',
    priority: 'essential',
    guidance: [
      'Map critical business functions',
      'Calculate actual business interruption needs',
      'Include key supplier disruption',
      'Review annually with business changes',
    ],
    guidanceTr: [
      'Kritik iş fonksiyonlarını haritalandırın',
      'Gerçek iş kesintisi ihtiyaçlarını hesaplayın',
      'Önemli tedarikçi kesintisini dahil edin',
      'İş değişiklikleriyle yıllık gözden geçirin',
    ],
    pitfalls: [
      'Underestimating recovery time',
      'Ignoring supply chain risks',
      'Static coverage in growing business',
    ],
    pitfallsTr: [
      'Kurtarma süresini hafife almak',
      'Tedarik zinciri risklerini görmezden gelmek',
      'Büyüyen işletmede statik teminat',
    ],
  },
  {
    id: 'business-bp-2',
    title: 'Cyber Risk Assessment',
    titleTr: 'Siber Risk Değerlendirmesi',
    description: 'Regular assessment of digital vulnerabilities',
    descriptionTr: 'Dijital güvenlik açıklarının düzenli değerlendirmesi',
    category: 'coverage',
    priority: 'essential',
    guidance: [
      'Conduct annual penetration testing',
      'Review cyber coverage with IT team',
      'Understand data breach notification requirements',
      'Include ransomware coverage',
    ],
    guidanceTr: [
      'Yıllık penetrasyon testi yapın',
      'Siber teminatı IT ekibiyle gözden geçirin',
      'Veri ihlali bildirim gereksinimlerini anlayın',
      'Fidye yazılımı teminatı dahil edin',
    ],
    pitfalls: [
      'Outdated security measures void coverage',
      'Missing sub-limits for ransomware',
      'No coverage for business email compromise',
    ],
    pitfallsTr: [
      'Güncel olmayan güvenlik önlemleri teminatı geçersiz kılar',
      'Fidye yazılımı için eksik alt limitler',
      'İş e-postası tehlikesi için teminat yok',
    ],
  },
]

export const BUSINESS_TEMPLATES: PolicyTemplate[] = [
  {
    id: 'business-standard',
    name: 'Standard Business Package',
    nameTr: 'Standart İşyeri Paketi',
    description: 'Comprehensive coverage for small to medium businesses',
    descriptionTr: 'Küçük ve orta işletmeler için kapsamlı teminat',
    policyType: 'business',
    tier: 'standard',
    audience: 'small_business',
    useCases: ['first_time_buyer', 'comprehensive_review'],
    coverages: BUSINESS_COVERAGES_STANDARD,
    estimatedPremiumRange: { min: 15000, max: 50000, typical: 25000 },
    bestPractices: BUSINESS_BEST_PRACTICES,
    highlights: [
      'Property and liability combined',
      'Business interruption coverage',
      'Cyber liability included',
      'Employer liability coverage',
    ],
    highlightsTr: [
      'Mülk ve sorumluluk birleşik',
      'İş kesintisi teminatı',
      'Siber sorumluluk dahil',
      'İşveren sorumluluğu teminatı',
    ],
    suitableFor: ['SMEs with 5-50 employees', 'Retail stores', 'Offices', 'Service businesses'],
    suitableForTr: ['5-50 çalışanlı KOBİler', 'Perakende mağazaları', 'Ofisler', 'Hizmet işletmeleri'],
    notSuitableFor: ['Manufacturing', 'High-risk industries', 'Large corporations'],
    notSuitableForTr: ['İmalat', 'Yüksek riskli sektörler', 'Büyük şirketler'],
    version: '1.0',
    lastUpdated: '2024-12-01',
    source: 'market_analysis',
    tags: ['business', 'sme', 'package', 'cyber'],
    tagsTr: ['işyeri', 'kobi', 'paket', 'siber'],
  },
]

// =============================================================================
// Health Insurance Templates
// =============================================================================

const HEALTH_COVERAGES_STANDARD: TemplateCoverage[] = [
  {
    name: 'Inpatient Care',
    nameTr: 'Yatarak Tedavi',
    category: 'core',
    description: 'Hospital stays and surgeries',
    descriptionTr: 'Hastane yatışları ve ameliyatlar',
    minLimit: 500000,
    recommendedLimit: 1500000,
    maxLimit: 10000000,
    typicalDeductible: 0,
    importance: 'critical',
    rationale: 'Essential for major medical events',
    rationaleTr: 'Büyük tıbbi olaylar için gerekli',
    watchExclusions: ['pre-existing conditions', 'cosmetic surgery'],
    watchExclusionsTr: ['mevcut hastalıklar', 'estetik cerrahi'],
  },
  {
    name: 'Outpatient Care',
    nameTr: 'Ayakta Tedavi',
    category: 'core',
    description: 'Doctor visits and diagnostics',
    descriptionTr: 'Doktor ziyaretleri ve teşhisler',
    minLimit: 50000,
    recommendedLimit: 150000,
    maxLimit: 500000,
    typicalDeductible: 100,
    importance: 'high',
    rationale: 'Regular healthcare access',
    rationaleTr: 'Düzenli sağlık erişimi',
    watchExclusions: ['alternative medicine', 'wellness visits'],
    watchExclusionsTr: ['alternatif tıp', 'sağlıklı yaşam ziyaretleri'],
  },
  {
    name: 'Prescription Drugs',
    nameTr: 'Reçeteli İlaçlar',
    category: 'core',
    description: 'Medication coverage',
    descriptionTr: 'İlaç teminatı',
    minLimit: 25000,
    recommendedLimit: 75000,
    maxLimit: 250000,
    typicalDeductible: 50,
    importance: 'high',
    rationale: 'Ongoing medication needs',
    rationaleTr: 'Süregelen ilaç ihtiyaçları',
    watchExclusions: ['non-generic drugs', 'off-label use'],
    watchExclusionsTr: ['jenerik olmayan ilaçlar', 'endikasyon dışı kullanım'],
  },
  {
    name: 'Dental',
    nameTr: 'Diş',
    category: 'recommended',
    description: 'Dental care and procedures',
    descriptionTr: 'Diş bakımı ve işlemler',
    minLimit: 5000,
    recommendedLimit: 15000,
    maxLimit: 50000,
    typicalDeductible: 200,
    importance: 'medium',
    rationale: 'Regular dental care prevents issues',
    rationaleTr: 'Düzenli diş bakımı sorunları önler',
    watchExclusions: ['cosmetic dentistry', 'orthodontics'],
    watchExclusionsTr: ['estetik diş hekimliği', 'ortodonti'],
  },
  {
    name: 'Maternity',
    nameTr: 'Doğum',
    category: 'optional',
    description: 'Pregnancy and childbirth coverage',
    descriptionTr: 'Hamilelik ve doğum teminatı',
    minLimit: 50000,
    recommendedLimit: 150000,
    maxLimit: 500000,
    typicalDeductible: 0,
    importance: 'medium',
    rationale: 'Essential for family planning',
    rationaleTr: 'Aile planlaması için gerekli',
    watchExclusions: ['fertility treatments', 'complications from prior pregnancies'],
    watchExclusionsTr: ['tüp bebek tedavileri', 'önceki hamileliklerdeki komplikasyonlar'],
  },
]

export const HEALTH_TEMPLATES: PolicyTemplate[] = [
  {
    id: 'health-standard',
    name: 'Standard Health Plan',
    nameTr: 'Standart Sağlık Planı',
    description: 'Balanced health coverage for individuals and families',
    descriptionTr: 'Bireyler ve aileler için dengeli sağlık teminatı',
    policyType: 'health',
    tier: 'standard',
    audience: 'family',
    useCases: ['first_time_buyer', 'renewal'],
    coverages: HEALTH_COVERAGES_STANDARD,
    estimatedPremiumRange: { min: 10000, max: 35000, typical: 20000 },
    bestPractices: [
      {
        id: 'health-bp-1',
        title: 'Network Hospital Selection',
        titleTr: 'Anlaşmalı Hastane Seçimi',
        description: 'Choose policy with preferred hospital network',
        descriptionTr: 'Tercih edilen hastane ağı ile poliçe seçin',
        category: 'coverage',
        priority: 'essential',
        guidance: [
          'Verify preferred doctors are in-network',
          'Check emergency coverage outside network',
          'Review hospital quality ratings',
        ],
        guidanceTr: [
          'Tercih edilen doktorların ağda olduğunu doğrulayın',
          'Ağ dışı acil teminatını kontrol edin',
          'Hastane kalite derecelendirmelerini gözden geçirin',
        ],
        pitfalls: [
          'Higher costs for out-of-network care',
          'Limited specialist access',
          'Travel required for specialized care',
        ],
        pitfallsTr: [
          'Ağ dışı bakım için daha yüksek maliyetler',
          'Sınırlı uzman erişimi',
          'Özel bakım için seyahat gerekli',
        ],
      },
    ],
    highlights: [
      'Inpatient and outpatient coverage',
      'Prescription drug coverage',
      'Dental included',
      'Optional maternity add-on',
    ],
    highlightsTr: [
      'Yatarak ve ayakta tedavi teminatı',
      'Reçeteli ilaç teminatı',
      'Diş dahil',
      'İsteğe bağlı doğum eklentisi',
    ],
    suitableFor: ['Families', 'Working professionals', 'Health-conscious individuals'],
    suitableForTr: ['Aileler', 'Çalışan profesyoneller', 'Sağlık bilincinde bireyler'],
    notSuitableFor: ['Minimal healthcare needs', 'Young singles', 'Employer-covered individuals'],
    notSuitableForTr: ['Minimal sağlık ihtiyaçları', 'Genç bekarlar', 'İşveren teminatlı bireyler'],
    version: '1.0',
    lastUpdated: '2024-12-01',
    source: 'market_analysis',
    tags: ['health', 'family', 'comprehensive', 'dental'],
    tagsTr: ['sağlık', 'aile', 'kapsamlı', 'diş'],
  },
]

// =============================================================================
// All Templates Export
// =============================================================================

export const ALL_TEMPLATES: Record<PolicyType, PolicyTemplate[]> = {
  home: HOME_TEMPLATES,
  kasko: KASKO_TEMPLATES,
  business: BUSINESS_TEMPLATES,
  health: HEALTH_TEMPLATES,
  traffic: [], // Add when needed
  life: [], // Add when needed
  dask: [], // Add when needed
}

/**
 * Get templates by policy type
 */
export function getTemplatesByType(policyType: PolicyType): PolicyTemplate[] {
  return ALL_TEMPLATES[policyType] || []
}

/**
 * Get template by ID
 */
export function getTemplateById(templateId: string): PolicyTemplate | null {
  for (const templates of Object.values(ALL_TEMPLATES)) {
    const found = templates.find((t) => t.id === templateId)
    if (found) return found
  }
  return null
}

/**
 * Get templates by tier
 */
export function getTemplatesByTier(tier: CoverageTier): PolicyTemplate[] {
  return Object.values(ALL_TEMPLATES)
    .flat()
    .filter((t) => t.tier === tier)
}

/**
 * Get all templates as flat array
 */
export function getAllTemplates(): PolicyTemplate[] {
  return Object.values(ALL_TEMPLATES).flat()
}
